-- Additional existing facts; no new facts and no field-specific interpreter branches.
INSERT INTO field_definition(id,code,name,scope,value_type,source_kind,is_system,source_ast,definition_version,provenance) VALUES
(md5('rule-field:EXIT_REASON')::uuid,'EXIT_REASON','Причина выбытия','ANIMAL','TEXT','CALCULATED',true,'{"op": "EVENT_VALUE", "event": "EXITED", "order": "DESC", "position": 1, "scope": "LIFETIME", "value": "reason"}',1,'{"source": "typed event details", "selection": "effective event order; null retained; dates farm-local", "policy": "latest effective fact, no non-null fallback"}'),
(md5('rule-field:FIRST_INSEMINATION_DATE_CURRENT_LACTATION')::uuid,'FIRST_INSEMINATION_DATE_CURRENT_LACTATION','Дата 1-го осеменения','ANIMAL','DATE','CALCULATED',true,'{"op": "EVENT_DATE", "event": "INSEMINATED", "order": "ASC", "position": 1, "scope": "CURRENT_LACTATION"}',1,'{"source": "typed event details", "selection": "effective event order; null retained; dates farm-local", "policy": "current lactation begins at last effective CALVED; absent CALVED -> null"}'),
(md5('rule-field:THIRD_INSEMINATION_DATE_CURRENT_LACTATION')::uuid,'THIRD_INSEMINATION_DATE_CURRENT_LACTATION','Дата 3-го осеменения','ANIMAL','DATE','CALCULATED',true,'{"op": "EVENT_DATE", "event": "INSEMINATED", "order": "ASC", "position": 3, "scope": "CURRENT_LACTATION"}',1,'{"source": "typed event details", "selection": "effective event order; null retained; dates farm-local", "policy": "current lactation begins at last effective CALVED; absent CALVED -> null"}'),
(md5('rule-field:LAST_WEIGHT_DATE')::uuid,'LAST_WEIGHT_DATE','Дата последнего взвешивания','ANIMAL','DATE','CALCULATED',true,'{"op": "EVENT_DATE", "event": "MEASURED", "order": "DESC", "position": 1, "scope": "LIFETIME", "where": {"measurement_code": "WEIGHT"}}',1,'{"source": "typed event details", "selection": "effective event order; null retained; dates farm-local", "policy": "latest effective fact, no non-null fallback"}'),
(md5('rule-field:PREVIOUS_WEIGHT_DATE')::uuid,'PREVIOUS_WEIGHT_DATE','Дата предпоследнего взвешивания','ANIMAL','DATE','CALCULATED',true,'{"op": "EVENT_DATE", "event": "MEASURED", "order": "DESC", "position": 2, "scope": "LIFETIME", "where": {"measurement_code": "WEIGHT"}}',1,'{"source": "typed event details", "selection": "effective event order; null retained; dates farm-local", "policy": "latest effective fact, no non-null fallback"}'),
(md5('rule-field:LAST_CALVING_DIFFICULTY')::uuid,'LAST_CALVING_DIFFICULTY','Трудность отела','ANIMAL','INTEGER','CALCULATED',true,'{"op": "EVENT_VALUE", "event": "CALVED", "order": "DESC", "position": 1, "scope": "LIFETIME", "value": "difficulty"}',1,'{"source": "typed event details", "selection": "effective event order; null retained; dates farm-local", "policy": "latest effective fact, no non-null fallback"}'),
(md5('rule-field:CURRENT_LACTATION_START_DATE')::uuid,'CURRENT_LACTATION_START_DATE','Дата начала тек.лакт','ANIMAL','DATE','CALCULATED',true,'{"op": "EVENT_DATE", "event": "CALVED", "order": "DESC", "position": 1, "scope": "LIFETIME"}',1,'{"source": "typed event details", "selection": "effective event order; null retained; dates farm-local", "policy": "latest effective fact, no non-null fallback"}');
UPDATE animal_rule_projection_snapshot SET stale=true WHERE singleton;
